app/__init__.py
from flask import Flask


def create_app():
  app = Flask(__name__)

  from .main import main as main_bp
  app.register_blueprint(main_bp)

  return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from . import main
from flask import render_template
from ..api.covid_data import total_kasus, get_data, kasus_per_kabupaten
from ..covid_content.news_update import get_news

RSS_FEEDS = {
  'indo_gov': 'https://covid19.go.id/feed/berita'
}

@main.route('/')
def index():
  return render_template('index.html', total_kasus=total_kasus(), data=get_data(), kasus_per_kabupaten=kasus_per_kabupaten())

@main.route('/news')
def news():
  news_update = get_news(RSS_FEEDS['indo_gov'])
  articles = [i for i in news_update.get('posts')[:6]]

  return render_template('news.html', articles=articles, news_update=news_update)

@main.route('/about')
def about():
  urls = {
    'github': 'https://github.com/superiorkid',
    'api': 'https://corona.ntbprov.go.id/api/data',
    'rss_feed': 'https://covid19.go.id/feed/berita'
  }

  return render_template('about.html', urls=urls)

app/templates/about.html
{% extends 'base.html' %}


{% block content %}
  <h3>Find me on github <a href="https://github.com/superiorkid">superiorkid</a></h3>
{% endblock content %}
  

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>West Nusa Tenggara Covid Information Center</title>

  <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap-extended.min.css">
  <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/fonts/simple-line-icons/style.min.css">
  <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/colors.min.css">
  <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap.min.css">

</head>
<body>

  <header style="background: #4C3571;padding:50px 0;">
    <div class="container">
      <h1 style="color: #fff;">Pusat Informasi Covid</h1>
      <span style="color: #fff;">Nusa Tenggara Barat</span>
    </div>
  </header>
  
  <div class="container">
  <nav class="navbar navbar-expand-sm">
  
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index')}}">
              Beranda
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.news') }}">
              Berita
            </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about')}}">
            Tentang
          </a>
      </li>
    </ul>
</nav>
</div>

<div class="container">
  
    {% block content %}
      
    {% endblock content %}
    
    
    <hr>
    <footer>
        <div class="row">
            <div class="col-md-6">
                <p>Copyright ©2022</p>
            </div>
        </div>
    </footer>
</div>

</script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="p-5 my-4 rounded-3">
  <h1>Covid-19 / Coronavirus Disease 2019</h1>
  <p class="lead">adalah penyakit akibat infeksi virus severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). COVID-19 dapat menyebabkan gangguan sistem pernapasan, mulai dari gejala yang ringan seperti flu, hingga infeksi paru-paru, seperti pneumonia.</p>
  <a href="{{ url_for('main.news') }}">Berita Covid-19 Terbaru...</a>
</div>

<div class="row">

<!-- Total Kasus -->
<div class="col-xl-3 col-sm-6 col-12">
  <div class="card">
    <div class="card-content">
      <div class="card-body">
        <div class="media d-flex">
          <div class="media-body text-left">
            <h3 class="danger">{{ total_kasus.get('total') }}</h3>
            <span>Kasus</span>
          </div>
          <div class="align-self-center">
            <i class="icon-user success font-large-2 float-right"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Sembuh -->
<div class="col-xl-3 col-sm-6 col-12">
  <div class="card">
    <div class="card-content">
      <div class="card-body">
        <div class="media d-flex">
          <div class="media-body text-left">
            <h3 class="success">{{ total_kasus.get('sembuh')}}</h3>
            <span>Sembuh</span>
          </div>
          <div class="align-self-center">
            <i class="icon-plus danger font-large-2 float-right"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- meninggal -->
<div class="col-xl-3 col-sm-6 col-12">
  <div class="card">
    <div class="card-content">
      <div class="card-body">
        <div class="media d-flex">
          <div class="media-body text-left">
            <h3 class="warning">{{ total_kasus.get('meninggal') }}</h3>
            <span>Meninggal</span>
          </div>
          <div class="align-self-center">
            <i class="icon-graph warning font-large-2 float-right"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Isolasi -->
<div class="col-xl-3 col-sm-6 col-12">
  <div class="card">
    <div class="card-content">
      <div class="card-body">
        <div class="media d-flex">
          <div class="media-body text-left">
            <h3 class="primary">{{ total_kasus.get('masih_isolasi') }}</h3>
            <span>Masih di Isolasi</span>
          </div>
          <div class="align-self-center">
            <i class="icon-support primary font-large-2 float-right"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<div class="row">
  <div class="col-12 mt-3 mb-1">
    <h4 class="text-uppercase">Kasus per-Kabupaten/Kota</h4>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Kabupaten/Kota</th>
      <th scope="col">Kasus</th>
      <th scope="col">Sembuh</th>
      <th scope="col">Meninggal</th>
      <th scope="col">Masih di Isolasi</th>
    </tr>
  </thead>
  <tbody>
    
    {% for key, value in kasus_per_kabupaten.items() %}

    <tr>

      <td>{{ loop.index }}</td>
      <td>{{key}}</td>
      <td>{{value[0] + value[1] + value[2]}}</td>
      <td>{{value[1]}}</td>
      <td>{{value[2]}}</td>
      <td>{{value[0]}}</td>

    </tr>

   
    {% endfor %}

  </tbody>
</table>

<div class="alert alert-warning justify-content-end" role="alert">
  <p>Update:  {{ data.get('update_terakhir') }} WITA</p>
</div>      

{% endblock content %}
  

app/templates/news.html
{% extends 'base.html' %}


{% block content %}
<div class="p-5 my-4 rounded-3">
  <h1>Covid-19 / Coronavirus Disease 2019</h1>
  <p class="lead">adalah penyakit akibat infeksi virus severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). COVID-19 dapat menyebabkan gangguan sistem pernapasan, mulai dari gejala yang ringan seperti flu, hingga infeksi paru-paru, seperti pneumonia.</p>
  <a href="{{ url_for('main.index') }}">Perkembangan Covid-19 di NTB</a>
</div>

<div class="row">
  <div class="col-12 mt-3 mb-1">
    <h4 class="text-uppercase">Berita Covid Terbaru</h4>
  </div>
</div>

<section id="gallery">
  <div class="container">
    <div class="row">      
      {% for article in articles %}
      <!-- <div class="col-lg-4 mb-4"> -->
        <div class="col-lg-4 d-flex align-items-stretch">
        <div class="card">
          <img src="{{ article.media_thumbnail }}" alt="" class="card-img-top" height="270">
          <div class="card-body">
            <h5 class="card-title">{{article.title}}</h5>
            <p class="card-text">{{article.summary}}</p>
           <a href="{{ article.link }}" class="btn btn-outline-success btn-sm">Read More</a>
          </div>
         </div>
        </div>      
      {% endfor %}
      <p>Sumber : <a href="{{ news_update.get('blog_link') }}"><u>covid19.go.id | {{ news_update.get('blog_title') }}</u></a></p>
  </div>
</div>
</section>


{% endblock content %}
  